import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import { Suspense } from "react"
import StoreInitializer from "@/components/StoreInitializer"
import { Contacts } from "@/types/contacts"
import { getContactsFromAPIData } from "./actions/contact_api"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const API_PATH =
    "https://my.api.mockaroo.com/lestetelecom/test.json?key=f55c4060"

  // const data = await fetch("http://localhost:3000/api")
  //   .then((res) => res.json())
  //   .then((data: Contacts) => data)
  const data = await getContactsFromAPIData()

  return (
    <html lang="en">
      <body className={inter.className}>
        <Suspense fallback={<div>Loading...</div>}>
          <StoreInitializer data={data}>{children}</StoreInitializer>
        </Suspense>
      </body>
    </html>
  )
}
